import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from db.base_class import Base
import db.models  # Ensure all models are registered with Base.metadata
# Use a separate test database for integration tests
SQLALCHEMY_DATABASE_URL = "sqlite:///./integration_test_fresh.db"
engine = create_engine(SQLALCHEMY_DATABASE_URL, connect_args={"check_same_thread": False})
TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# Patch SessionLocal globally BEFORE importing app
import db.session
db.session.SessionLocal = TestingSessionLocal

from api.main import app
from api.dependencies import get_db

Base.metadata.create_all(bind=engine)

# Also patch modules that imported it directly
import ml.training.train
ml.training.train.SessionLocal = TestingSessionLocal
import api.middleware
api.middleware.SessionLocal = TestingSessionLocal
import prompts.prompt_manager
prompts.prompt_manager.SessionLocal = TestingSessionLocal

def override_get_db():
    try:
        db = TestingSessionLocal()
        yield db
    finally:
        db.close()

app.dependency_overrides[get_db] = override_get_db

client = TestClient(app)

def test_full_lifecycle():
    # 1. Check health
    response = client.get("/health")
    assert response.status_code == 200
    
    # 2. Check metrics endpoint
    response = client.get("/api/v1/metrics")
    assert response.status_code == 200
    assert "system" in response.json()
    
    # 3. Create a Goal Plan (this runs ML prediction + LLM Generation + DB Storage)
    goal_payload = {
        "title": "Integration Test Goal",
        "description": "This is a full end-to-end test goal.",
        "category": "Career"
    }
    
    response = client.post("/api/v1/generate-goal-plan", json=goal_payload)
    assert response.status_code == 200
    data = response.json()
    
    assert "goal_id" in data
    assert "plan_data" in data
    assert "metadata" in data
    assert data["metadata"]["difficulty"] in ["Easy", "Medium", "Hard"]
    
    goal_id = data["goal_id"]
    plan_id = goal_id # Assuming 1:1 mapping in SQLite autoincrement for this test
    
    # 4. Submit Feedback
    feedback_payload = {
        "goal_plan_id": plan_id,
        "rating": 5,
        "comments": "Excellent plan generated by AI!"
    }
    
    response = client.post("/api/v1/feedback/", json=feedback_payload)
    assert response.status_code == 200
    assert response.json()["message"] == "Feedback submitted successfully. Thank you!"

    # 5. Check History
    response = client.get("/api/v1/history")
    assert response.status_code == 200
    history = response.json()
    assert len(history) > 0
    assert history[0]["title"] == "Integration Test Goal"
