apiVersion: v1
kind: Service
metadata:
  name: goalplanner-api-svc
  namespace: goalplanner
spec:
  type: ClusterIP
  selector:
    app: goalplanner-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
